# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True)),
                ('game_name', models.CharField(max_length=512, verbose_name='\u6e38\u620f\u540d\u79f0')),
                ('url_update', models.CharField(default='', max_length=512, verbose_name='\u66f4\u65b0\u5730\u5740')),
                ('game_server', models.CharField(max_length=512, verbose_name='\u670d\u52a1\u5668\u5730\u5740')),
                ('game_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='\u7537', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u6a21\u5757\u540d\u79f0')),
                ('debug_version', models.IntegerField()),
                ('release_version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='\u73a9\u5bb6\u540d\u79f0')),
                ('uuid', models.CharField(max_length=512, verbose_name='\u8bbe\u5907\u6807\u8bc6\u7801')),
                ('platform', models.CharField(max_length=128, verbose_name='\u5e73\u53f0')),
            ],
        ),
    ]
