# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u6a21\u5757\u540d\u79f0')),
                ('debug_version', models.IntegerField()),
                ('release_version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='\u73a9\u5bb6\u540d\u79f0')),
                ('uuid', models.CharField(max_length=512, verbose_name='\u8bbe\u5907\u6807\u8bc6\u7801')),
                ('platform', models.CharField(max_length=128, verbose_name='\u5e73\u53f0')),
            ],
        ),
    ]
